import warnings
import pyttsx3
import webbrowser
import wikipedia
from datetime import datetime
from urllib.parse import quote

# Ignore the warning generated by the wikipedia package
warnings.filterwarnings("ignore")

# Text-to-speech setup
engine = pyttsx3.init()
engine.setProperty("rate", 190)
engine.setProperty("volume", 1.0)

def talk(message):
    print(f"  ASKY : {message}")
    engine.stop()
    engine.say(message)
    engine.runAndWait()

def greet():
    hour = datetime.now().hour
    if 6 <= hour < 12:
        greeting = "Good Morning"
    elif 12 <= hour < 16:
        greeting = "Good Afternoon"
    elif 16 <= hour < 23:
        greeting = "Good Evening"
    else:
        greeting = "Good Night"
    talk(
        f"{greeting}. \n\tI am asky, "
        "( Artificial Solutions and Knowledge Yield. )"
        f"\n\tHow can I assist you? "
    )
    
def open_website(url):
    webbrowser.open(url)

def search_youtube(query):
    talk(f"Searching YouTube for {query}.")
    query = quote(query)
    open_website(
        f"https://www.youtube.com/results?search_query={query}"
    )

def search_google(query):
    talk(f"Searching Google for {query}.")
    query = quote(query)
    open_website(
        f"https://www.google.com/search?q={query}"
    )


def search_wikipedia(topic):
    try:
        result = wikipedia.summary(topic, sentences=2)
        talk(result)

    except wikipedia.exceptions.DisambiguationError:
        talk("There are multiple results. Please be more specific.")

    except wikipedia.exceptions.PageError:
        talk("Sorry, I could not find that topic.")

    except Exception as e:
        print(e)
        talk("Something went wrong while searching Wikipedia.")


def main():
    exit_commands = [
        "bye",
        "exit",
        "close",
        "shutdown",
        "done"
    ]

    while True:

        user = input("  You : ").lower().strip()

        # Exit the assistant
        if user in exit_commands:

            talk("Okay, shutting down ASKY.")

            break

        # Open YouTube
        elif user.startswith("open youtube"):

            talk("Opening YouTube.")

            open_website("https://www.youtube.com")

        # Search something on YouTube
        elif "search" in user and "youtube" in user:

            query = user.replace("search", "")
            query = query.replace("youtube", "")
            query = query.replace("on", "")
            query = query.strip()

            if query:

                search_youtube(query)

            else:

                talk("What should I search on YouTube?")

        # Open Google
        elif user.startswith("open google"):

            talk("Opening Google.")

            open_website("https://www.google.com")

        # Search something on Google
        elif "search" in user and "google" in user:

            query = user.replace("search", "")
            query = query.replace("google", "")
            query = query.replace("on", "")
            query = query.strip()

            if query:

                search_google(query)

            else:

                talk("What should I search on Google?")

        # Search Wikipedia
        elif "wikipedia" in user:

            topic = user.replace("wikipedia", "")
            topic = topic.replace("search", "")
            topic = topic.strip()

            if topic:

                search_wikipedia(topic)

            else:

                talk("What should I search on Wikipedia?")

        # Tell the current time
        elif "time" in user:

            current_time = datetime.now().strftime("%I:%M %p")

            talk(
                f"The current time is {current_time}."
            )

        # Unknown command
        else:

            talk("I don't know how to perform that task yet.")


if __name__ == "__main__":

    greet()

    main()
